code --install-extension esbenp.prettier-vscode --force
code --install-extension formulahendry.auto-close-tag --force
code --install-extension formulahendry.auto-complete-tag --force
code --install-extension formulahendry.auto-rename-tag --force
code --install-extension beardedbear.beardedtheme --force
code --install-extension aaron-bond.better-comments --force
code --install-extension streetsidesoftware.code-spell-checker --force
code --install-extension usernamehw.errorlens --force
code --install-extension dsznajder.es7-react-js-snippets --force
code --install-extension github.copilot --force
code --install-extension eamodio.gitlens --force
code --install-extension wix.vscode-import-cost --force
code --install-extension pkief.material-icon-theme --force
code --install-extension esbenp.prettier-vscode --force
code --install-extension ms-vscode-remote.remote-ssh --force
code --install-extension prisma.prisma --force
code --install-extension orta.vscode-jest --force 
code --install-extension GitHub.copilot --force
